filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true 
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'php-clover'

    environment:
        php:
            version: 7.0
tools:
    php_sim: false
    php_cpd: false