filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true 
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                command: 'tools/phpunit --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'php-clover'

    dependencies:
        before:
            - 'wget https://phar.io/releases/phive.phar'
            - 'wget https://phar.io/releases/phive.phar.asc'
            - 'gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0x9B2D5D79'
            - 'gpg --verify phive.phar.asc phive.phar'
            - 'gpg --keyserver pgp.uni-mainz.de --recv-keys 0x4AA394086372C20A'
            - 'php phive.phar install'
    environment:
        php:
            version: 5.6.9
tools:
    php_sim: false
    php_cpd: false