filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true 
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    tests:
        override:
            -
                command: 'php phpunit.phar --coverage-clover=coverage-file'
                coverage:
                    file: 'coverage-file'
                    format: 'php-clover'

    dependencies:
        before:
            - 'wget https://phar.phpunit.de/phpunit.phar'
    environment:
        php:
            version: 7.1.0
tools:
    php_sim: false
    php_cpd: false